### ISSUE TITLE
Add wayland support

### ISSUE THREAD

**Issue by SilverLuke** [hezral/keystrokes#14]
Right now I am getting this error : 
```
Traceback (most recent call last):
  File "/app/bin/keystrokes", line 22, in <module>
    from keystrokes import main
  File "/app/share/com.github.hezral.keystrokes/keystrokes/main.py", line 13, in <module>
    from .window import KeystrokesWindow
  File "/app/share/com.github.hezral.keystrokes/keystrokes/window.py", line 12, in <module>
    from .key_event import MouseListener, KeyListener
  File "/app/share/com.github.hezral.keystrokes/keystrokes/key_event.py", line 4, in <module>
    from pynput import keyboard, mouse
  File "/app/lib/python3.8/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/app/lib/python3.8/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/app/lib/python3.8/site-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
```
Running on gnome 42 Mutter (Wayland) on linux 5.15.33-1-lts

**Comment by hezral** [comment]
Thanks for reporting this but Wayland isn't supported due to how Wayland works. I'm not sure if it will ever be supported as it relies on Wayland and the compositor.
